// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsroveljtrscsgkykmfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcm92ZWxqdHJzY3Nna3lrbWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTAxMjEsImV4cCI6MjA3MDIyNjEyMX0.7NE0xKtqHcIEobXKJnNycCZIgGwx_aIlZGhaZzY_nbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getSafeStorage = () => {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const test = '__sb_test__';
      window.localStorage.setItem(test, test);
      window.localStorage.removeItem(test);
      return window.localStorage;
    }
  } catch (e) {
    // Safari Private Browsing mode throws on localStorage
  }
  const memStorage: Record<string, string> = {};
  return {
    getItem: (key: string) => memStorage[key] || null,
    setItem: (key: string, value: string) => { memStorage[key] = value; },
    removeItem: (key: string) => { delete memStorage[key]; }
  };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});